[package]
name = "ink_lang_macro"
version = "2.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

license = "APACHE-2.0"
readme = "README.md"
repository = "https://github.com/paritytech/ink"
documentation = "https://substrate.dev/substrate-contracts-workshop/#/"
homepage = "https://www.parity.io/"
description = "[ink!] Rust based eDSL for writing smart contracts for Substrate"
keywords = ["wasm", "parity", "webassembly", "blockchain", "edsl"]
categories = ["no-std", "embedded"]
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE"]

[dependencies]
ink_primitives = { version = "2.1.0", path = "../../primitives/", default-features = false }

scale = { package = "parity-scale-codec", version = "1.3", default-features = false, features = ["derive"] }
quote = "1"
syn = { version = "1.0", features = ["parsing", "full", "extra-traits"] }
proc-macro2 = "1.0"
heck = "0.3"
itertools = { version = "0.9", default-features = false }
either = { version = "1.5", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1.0"
derive_more = { version = "0.99", default-features = false, features = ["from"] }
regex = "1.3"

[dev-dependencies]
ink_abi = { version = "2.1.0", path = "../../abi/" }
ink_core = { version = "2.1.0", path = "../../core/" }
ink_lang = { version = "2.1.0", path = "..", default-features = false, features = ["ink-generate-abi"] }

trybuild = "1.0.24"
pretty_assertions = "0.6.1"

[dependencies.type-metadata]
git = "https://github.com/type-metadata/type-metadata.git"
rev = "02eae9f35c40c943b56af5b60616219f2b72b47d"
default-features = false
features = ["derive"]

[lib]
name = "ink_lang_macro"
proc-macro = true

[features]
default = ["std"]
std = [
    "scale/std",
    "itertools/use_std",
    "either/use_std",
    "ink_primitives/std",
    "serde/std",
]
ink-generate-abi = [
    "std",
]
